#include <bits/stdc++.h>

using namespace std;

//ACN
//ADS
//CRYPTO
//DL
//RA
//TIS
//SM
//MA1
//MA2

map<string, set<int>> students;

//uniform data generated by gpt for the research

void setStudents() {
    students.clear();

    vector<string> courses = {"ACN", "ADS", "CRYPTO", "DL", "RA", "TIS"};
    const int numCourses = (int)courses.size();

    // prepare roll numbers: 101..166 and 201..265
    vector<int> rolls;
    for (int r = 101; r <= 166; ++r) rolls.push_back(r);
    for (int r = 201; r <= 265; ++r) rolls.push_back(r);

    for(int r = 101; r <= 166; r++) {
        students["SM1"].insert(r);
        students["MA1"].insert(r);
    }
    for(int r = 201; r <= 265; r++) {
        students["SM2"].insert(r);
        students["MA2"].insert(r);
    }

    // counts aligned with courses vector
    vector<int> counts(numCourses, 0);

    for (int roll : rolls) {
        // indices 0..numCourses-1
        vector<int> idx(numCourses);
        for (int i = 0; i < numCourses; ++i) idx[i] = i;

        // sort indices by (count, index) so we pick smallest-count courses, deterministic tie-breaker
        sort(idx.begin(), idx.end(), [&](int a, int b) {
            if (counts[a] != counts[b]) return counts[a] < counts[b];
            return a < b;
        });

        // assign this student to the first 3 courses from sorted idx
        for (int k = 0; k < 3; ++k) {
            int ci = idx[k];
            students[courses[ci]].insert(roll);
            ++counts[ci];
        }
    }
}

//add to score when
//current i'th hr class there
//next hr i.e. (i + 1)'th hr class there

//students[next_class] intersection students[current_class]

float getCommonCount(string c1, string c2) {
    if(c1 == "EMPTY" || c2 == "EMPTY") {
        return 0;
    }

    int cnt = 0;

    for(int i = 101; i <= 265; ) {
        if(i == 167) {
            i = 201;
            continue;
        }
        auto it1 = students.find(c1);
        auto it2 = students.find(c2);
        if(it1 == students.end() || it2 == students.end()) continue;
        if(it1->second.find(i) != it1->second.end() && it2->second.find(i) != it2->second.end()) {
            cnt++;
        }
        i++;
    }

    return cnt;
}

float computeScore(vector<vector<string>> slots) {
    int score = 0;
    
    for(int day = 0; day < 5; day++) {
        for(int i = 1; i <= 6; i++) {
            if(i == 4) continue;
            score += getCommonCount(slots[day][i - 1], slots[day][i]);
        }   
    }

    return (float)score / 10;
}

int computePenalty(vector<vector<string>> slots) {
    int totPenalty = 0;
    int student = 101;

    while(student <= 265) {
        if(student == 167) {
            student = 201;
            continue;
        }

        int currPenalty = 0;

        for(int day = 0; day < 5; day++) {
            int last = -1;
            for(int slot = 0; slot <= 6; slot++) {
                string course = slots[day][slot];
                auto it = students.find(course);
                if(it != students.end() && it->second.find(student) != it->second.end()) {
                    if(last != -1) currPenalty += slot - last - 1;
                    last = slot;
                }
            }
        }

        totPenalty += currPenalty;

        student++;
    }

    return totPenalty;
}

int main() {

    vector<vector<string>> slots(5, vector<string>(7));
    slots[0] = {"RA", "EMPTY", "ACN", "TIS", "CRYPTO", "DL", "ADS"};
    slots[1] = {"RA", "EMPTY", "ADS", "DL", "ACN", "TIS", "CRYPTO"};
    slots[2] = {"RA", "MA2", "SM2", "DL", "TIS", "CRYPTO", "ADS"};
    slots[3] = {"ADS", "EMPTY", "MA2", "SM2", "ACN", "TIS", "DL"};
    slots[4] = {"CRYPTO", "ACN", "MA2", "EMPTY", "EMPTY", "EMPTY", "EMPTY"};

    setStudents();
    float score = computeScore(slots);
    float penalty = computePenalty(slots);
    cout << "Score: " << score << '\n';
    cout << "Penalty: " << penalty;

    return 0;
}